Update @expo/config-plugins and move it to peerDependencies
fullstorydev/fullstory-react-native pull request #53
Opened 2022-12-08 23:53 UTC by pettomartino

Hi team,

I'm updating Expo to use SDK 47, however `expo doctor` complains about outdated version of `@expo/config-plugins`.

Would you accept this update?

2023-02-10 09:43 UTC, jlpopken commented
Hello all,

We are also using Expo to use SDK 47, and would love for this to be accepted. Thanks!

2023-02-24 09:48 UTC, pettomartino commented
This is a little bit more complicated than I thought.
The plugins use `import { mergeContents } from "@expo/config-plugins/build/utils/generateCode";` from version 4 that doesn't seem to be exported in version 5

2023-03-28 20:09 UTC, dereklucas commented
Have you had any issues with unmasking while using the resolution override?

2023-03-28 20:23 UTC, jwise commented
Hi folks - sorry we missed this for so long :) I confess that we're not quite set up to handle support via Github. Would you mind sending mail to mobile-support@fullstory.com as well, so we can track it through our normal processes and make sure that we don't drop it (and so we can get it linked with your customer accounts, too)?

2023-03-28 20:24 UTC, jwise commented
(And, by the way, thanks for this! I'm an iOS native guy so I'm not exactly the right person to review RN stuff but I definitely want to make sure we get the right eyes on this.)

2023-04-03 16:30 UTC, pettomartino commented
@dereklucas I haven't noticed any issue.

2023-04-10 15:29 UTC, RyanCommits requested changes
Use the recommended dependencies from Expo:
```
{
  "dependencies": {},
  "devDependencies": {
    "expo": "^47.0.0"
  },
  "peerDependencies": {
    "expo": ">=47.0.0"
  },
  "peerDependenciesMeta": {
    "expo": {
      "optional": true
    }
  }
}
```

2023-05-09 19:42 UTC, RyanCommits commented
Fixed with https://github.com/fullstorydev/fullstory-react-native/commit/b8af1ce7147c2dc5267272e5da137feeda277587.

2023-05-09 19:42 UTC, closed without merging