iOS Fabric implementation
fullstorydev/fullstory-react-native pull request #79
Opened 2023-10-31 14:14 UTC by RyanCommits

See [design doc](https://docs.google.com/document/d/1OIahWaovsaoqdWr12zmJRcF0LZlOzoDuLcv6FPzz_WY)

This work seeks to solve an issue where props are statically defined in Fabric and cannot set our FullStory props onto views.

2023-11-01 02:10 UTC, jwise requested changes
I see one 'in review' on DOC-1863, one 'unstarted', and one 'design approved'.  I still have some open questions from a few weeks ago, and I think @jth0024 does as well, that need to be answered before we merge this approach (probably we should add Jordan as a reviewer on DOC-1863, also).  I think it is possible that we can make this design work, but I'm not sure we're ready to commit to it based on the state of the design doc?

So I guess -1 for now on that front (and certainly there are style / functionality changes that are currently needed), but I don't fundamentally object to this design if we can show that it works well.

2023-11-01 02:10 UTC, jwise commented on src/index.ts
> +});
As I mentioned in the design doc, I'm still a little nervous about doing these sequentially.  Do we know what thread JavaScript runs on?  I guess it might be okay iff a view is added to the hierarchy only after our `applyFSPropertiesWithRef` completes.  But if that's the case we need to document that, ideally, in a way that shows why that is the case.

2023-11-01 02:10 UTC, jwise commented on src/index.ts
> +      const fsClass = element.currentProps['fsClass'];
I wonder if we could DRY this `currentProps is missing` thing by pulling `currentProps` into a local.  And broadly I wonder if we could DRY it by just iterating all of the `supportedCommands` or something rather than naming each one three times...

2023-11-01 14:39 UTC, RyanCommits commented
Sorry @jwise , I should've labeled this PR as work in progress. I wanted to get my `JS` changes up so that @martin-fs  can fill in his `iOS` work after. Martin has the latest Obj-c code which isn't in this PR yet

2023-11-09 15:54 UTC, martin-fs commented on ios/FullStory.mm
> +static void set_fsClass(id json, RCTView *view) {
I think a static function is the correct idiom to use when the functionality's use is limited to the current file. Extensions are meant to allow use across files - they add functions to the lookup table, and carry the risk of being referenced outside of their intended use.

2023-11-09 15:54 UTC, martin-fs commented on ios/FullStory.mm
> +    NSArray <NSString *>* classes = [(NSString *)json componentsSeparatedByString: @","];
I'm following the original code here to have minimal impact:
https://github.com/fullstorydev/fullstory-react-native/blob/45e21f3a7350c624221bfe9ab75639f3ef03ea9d/ios/FullStory.mm#L225-L228
The code has been in place for [over three years](https://github.com/fullstorydev/fullstory-react-native/pull/12) without issue.

It should not be possible with TS to include a non-string property in the Old Architecture:
https://github.com/fullstorydev/fullstory-react-native/blob/45e21f3a7350c624221bfe9ab75639f3ef03ea9d/src/index.ts#L62-L70
See the changes to `index.ts` below for the equivalent restriction in Fabric:
https://github.com/fullstorydev/fullstory-react-native/pull/79/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R90-R95

It seems appropriate to crash if a programmer attempts to subvert the type system. However, I could add a test here, and terminate FullStory if it is of the incorrect type, because continuing to capture is inappropriate if there is an attempt to set a privacy rule that cannot be handled. We would have to expose an API to terminate FullStory. This seems beyond the scope of this PR, but I would be happy to add it in a followup.

2023-11-09 15:54 UTC, martin-fs commented on ios/FullStory.mm
> +}
I'm not sure what you're referring to when you say `fs_cast` here - there is no reference to it in this repository. Perhaps this is an example of an extension being referenced outside of its intended use. [isKindOfClass](https://developer.apple.com/documentation/objectivec/1418956-nsobject/1418511-iskindofclass) is public API that can be used in the test I proposed above. Otherwise, crashing would be better than continuing to capture after ignoring a privacy rule, and seems like an appropriate response to an attempt to subvert the type system.

2023-11-09 15:55 UTC, martin-fs commented on src/index.ts
> +});
I believe your concerns were addressed in the discussion and design doc. I don't think it's appropriate to write an essay about React Native's architecture here.

2023-11-09 19:31 UTC, martin-fs commented on src/index.ts
> +      const fsClass = element.currentProps['fsClass'];
I looked at this and as far as I can tell, [it's not completely trivial](https://stackoverflow.com/a/45670960). Interface properties are not iterable and only exist at compile time unless customers implement custom transformers. Plugin support for custom transformers continues to be an [open issue after five years](https://github.com/Microsoft/TypeScript/issues/14419). This aesthetic issue should not be a blocking concern for this PR.

2023-11-13 22:07 UTC, prashanthsadasivan-fullstory approved these changes
the swizzles look good to me. some various small comments, but LGTM from my perspective.

2023-11-14 00:32 UTC, martin-fs commented on ios/FullStory.mm
> +                        NSAssert(strncmp(className, "RCT", 3) != 0, @"React Native framework class %s needs handleCommand support! Please contact FullStory support with this message.", className);
Yes, it would crash the app when it is running in debug mode. I agree that this would be very disruptive to the developer. However, it's kind of unsafe for them to use the SDK if this is the case. If we are worried that this assert will be triggered, we could instead swizzle all subclasses per the original design. Or, we could add a terminate-with-error-message method to the SDK in a followup PR and terminate with this error message instead of NSAssert.

2023-11-18 01:37 UTC, jwise commented on ios/FullStory.mm
> +    NSArray <NSString *>* classes = [(NSString *)json componentsSeparatedByString: @","];
Yes, I am OK with this if this is following the original.

2023-11-18 01:41 UTC, jwise commented on src/index.ts
> +});
Yes, my concerns about threading of this were addressed in the design doc.  It might be worth adding a comment to, if nothing else, point to the discussion in the design doc for why this is ok.

2023-11-18 01:48 UTC, jwise commented on src/index.ts
> +      const fsClass = element.currentProps['fsClass'];
Wow, big oof that we can't iterate over an interface.

I was kind of thinking something like (pseudocode):

```javascript
  for (prop in ['fsClass', 'fsAttribute', 'fsTagName', ...]) {
    // @ts-expect-error ...
    const val = element.currentProps[prop];
    if (val) {
      Commands[prop](element, val); /* will we need a ts waiver here? */
    }
  }
```

Something like this definitely has the chance to grow copy-and-paste errors if it needs to be touched later so if we can avoid repeating something six times, that might be nice.  If we were feeling *extremely* fancy, that list (`['fsClass', ...]`) could also be a `const` elsewhere that we could pass as the parameter to `codegenNativeCommands`, for one more repetition eliminated!

Or, if nothing else, hoisting out `const props = element.currentProps;`, so we only have to `@ts-expect-error` once.  What do you think about these?

2023-11-18 01:51 UTC, jwise commented on ios/FullStory.mm
> +static void set_fsClass(id json, RCTView *view) {
Ok, fair enough.  (Generally I tend to prefix static methods with `_`, and I tend to prefer the parameter order `object_verb_noun(object, parameters...)`, which in this case would translate to `_rctview_set_fsClass(RCTView *view, id json)`, just to scope things a little more tightly -- like we do two lines prior, scoping `_rctview_previous_attributes_key` by name -- but that could be a matter of taste.)

2023-11-18 02:00 UTC, jwise commented on ios/FullStory.mm
> +                        NSAssert(strncmp(className, "RCT", 3) != 0, @"React Native framework class %s needs handleCommand support! Please contact FullStory support with this message.", className);
I'm ok with this being a crashing NSAssert -- especially because a developer wanting to work around it doesn't need to wait for us to release a new plugin version, but instead can make the modification themselves in their local tree.  Nice work on checking this in debug.

2023-11-18 02:02 UTC, jwise commented on ios/FullStory.mm
> +                        NSLog(@"RCTViewComponentView subclass %s cannot receive FullStory commands", className);
```suggestion
                        NSLog(@"RCTViewComponentView subclass %s cannot receive FullStory commands; FullStory attributes on such views may not function correctly.  If you need to attach FullStory attributes to such views, please contact FullStory support with this message.", className);
```

2023-11-18 02:06 UTC, jwise commented on ios/FullStory.mm
> +#pragma clang diagnostic push
```suggestion
      // RCTViewComponentView subclasses don't tend to call their superclass implementations of handleCommand, so in debug mode, we want to make sure that we don't have any "straggler" classes (especially React core classes!) that don't have their implementations of handleCommand interposed.  We enumerate all the classes on the system, determine if any has a superclass of RCTViewComponentView, and if so, make sure that we have it covered.
#pragma clang diagnostic push
```

2023-11-18 02:07 UTC, jwise commented on ios/FullStory.mm
> +        // Install swizzle in all subclasses of RCTViewComponentView
```suggestion
        // Verify swizzle in all subclasses of RCTViewComponentView
```

2023-11-18 02:09 UTC, jwise approved these changes
ObjC changes LGTM.  I suggested a few comments and a few style changes, and it would be nice to see something to shore up the DRY situation down there in TS land, but I trust you to make those changes as appropriate.  Looks like an approach that is going to work out!

2023-11-20 21:51 UTC, RyanCommits commented on src/index.ts
> +      const fsClass = element.currentProps['fsClass'];
Hoisted the `element.currentProps` so we only have the `ts-expect-error` once. 

Improved types so copy-and-paste errors will be unlikely since it has to match the `NativeCommand` type.

2023-11-20 21:58 UTC, RyanCommits commented on src/index.ts
> +});
comment added

2023-11-20 22:00 UTC, merged